#!/usr/bin/env python
import sys
from libcrypclient import pad

def main():
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(
                usage = "%prog [options] output",
                version="%prog 0.1",
            )
    parser.add_option(
        "-c", "--converter", action="store_true",
        dest="converter", default=False,
        help = "Create the converter app."
    )
    parser.add_option(
        "-d", "--dev", action="store_true",
        dest="dev", default=False,
        help = "Include dev buttons."
    )
    parser.add_option(
        "-n", "--nomin", action="store_true",
        dest="nomin", default=False,
        help = "Don't minimize output."
    )
    parser.add_option(
        "-a", "--hash", action="store_true",
        dest="hash", default=False,
        help = "Calculate SHA256 hash."
    )
    parser.add_option(
        "-s", "--stats", action="store_true",
        dest="stats", default=False,
        help = "Display stats."
    )
    options, args = parser.parse_args()
    if not options.hash:
        if len(args) != 1:
            parser.error("Output file.")

    if options.converter:
        l = pad.Converter("http://testdomain/", not options.nomin, options.dev)
        output = l.render("name", "")
    else:
        l = pad.Pad("http://testdomain/", not options.nomin, options.dev)
        output = l.existing("name", "")

    if options.hash:
        print >> sys.stderr, pad.hash(output, True)
    if args:
        f = open(args[0], "w")
        f.write(output)
    if options.stats:
        print >> sys.stderr, "Size: %s bytes"%(len(output))

main()
